### ISSUE TITLE
Cannot save new account

### ISSUE THREAD

**Issue by brsgina** [spxbhuhb/zakadabar-stack#85]
There's something wrong with the validation

log.kt?6649:17 ClassCastException: Illegal cast
    at Object.captureStack (webpack-internal:///./kotlin-dce-dev/kotlin.js:38593:15)
    at ClassCastException.Exception [as constructor] (webpack-internal:///./kotlin-dce-dev/kotlin.js:38926:14)
    at ClassCastException.RuntimeException [as constructor] (webpack-internal:///./kotlin-dce-dev/kotlin.js:38952:17)
    at RuntimeException_init_0 (webpack-internal:///./kotlin-dce-dev/kotlin.js:38963:24)
    at new ClassCastException (webpack-internal:///./kotlin-dce-dev/kotlin.js:39082:7)
    at throwCCE_0 (webpack-internal:///./kotlin-dce-dev/kotlin.js:42811:13)
    at Form$CreateForm.validate_6taknv$$default (webpack-internal:///./kotlin-dce-dev/zakadabar-stack-accounts.js:4240:57)
    at Form$CreateForm.ZkForm.validate_6taknv$ (webpack-internal:///./kotlin-dce-dev/zakadabar-stack-core.js:22388:63)
    at Coroutine$ZkForm$submit$lambda.doResume (webpack-internal:///./kotlin-dce-dev/zakadabar-stack-core.js:22464:41)
    at Coroutine$queryOrNull_bjzaex$.CoroutineImpl.resumeWith_tl1gpc$ (webpack-internal:///./kotlin-dce-dev/kotlin.js:38764:35)

**Comment by toth-istvan-zoltan** [comment]
fixed in 2021.11.15.1
